
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - management.seldon.io
  resources:
  - seldonclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.seldon.io
  resources:
  - seldonclusters/finalizers
  verbs:
  - update
- apiGroups:
  - management.seldon.io
  resources:
  - seldonclusters/status
  verbs:
  - get
  - patch
  - update
