# permissions for end users to edit seldonclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: seldoncluster-editor-role
rules:
- apiGroups:
  - management.seldon.io.seldon.io
  resources:
  - seldonclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.seldon.io.seldon.io
  resources:
  - seldonclusters/status
  verbs:
  - get
