# permissions for end users to view seldonclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: seldoncluster-viewer-role
rules:
- apiGroups:
  - management.seldon.io
  resources:
  - seldonclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.seldon.io
  resources:
  - seldonclusters/status
  verbs:
  - get
